# Generated by Django 2.2 on 2019-07-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=100)),
                ('phonenumber', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('areaofinterest', models.CharField(max_length=100)),
            ],
        ),
    ]
