# Generated by Django 2.2 on 2019-07-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='areaofinterest',
            new_name='company',
        ),
    ]
