# Generated by Django 2.2 on 2019-07-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_auto_20190712_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='phonenumber',
            field=models.CharField(max_length=12),
        ),
    ]
